FROM python:2.7.13
ENV PYTHONUNBUFFERED 1

RUN set -ex && \
    echo 'deb http://deb.debian.org/debian jessie-backports main' \
      > /etc/apt/sources.list.d/jessie-backports.list && \

    apt update -y && \
    apt install -t \
      jessie-backports \
      openjdk-8-jre-headless \
      ca-certificates-java -y

RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash
RUN apt-get -y install nodejs 

RUN apt-get install -y -qq ruby-dev
RUN apt-get install -y rubygems
RUN apt-get install make

RUN gem install --no-rdoc --no-ri sass -v 3.4.22
RUN gem install --no-rdoc --no-ri compass -v 1.0.3

RUN mkdir /code

ADD requirements.txt /code/
ADD requirements/ /code/requirements/
ADD package.json /code/
WORKDIR /code

RUN pip install -r requirements.txt
RUN npm install
RUN npm install -g grunt-cli
